name: "Install cydonia"
description: "Install cydonia, the static site generator."

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/cydonia
        key: ${{ runner.os }}-cydonia
    - name: Install cydonia
      run: |
        BIN=~/.cargo/bin/cydonia
        if [ ! -f BIN ]; then
          cargo install cydonia
        fi
