name: "Install cydonia"
description: "Install cydonia, the static site generator."

inputs:
  version:
    description: "The version of cydonia to install"
    required: true
    default: "0.0.4"

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/cydonia
        key: cydonia-${{ inputs.version }}-${{ runner.os }}
        restore-keys: cydonia-

    - name: Find cydonia
      id: cache
      shell: bash
      run: |
        BIN=~/.cargo/bin/cydonia
        if [ ! -f $BIN ]; then
          echo "skip=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Install rust-toolchain
      id: install-rust
      if: ${{ steps.cache.outputs.skip == 'false' }}
      uses: dtolnay/rust-toolchain@stable

    - name: Install cydonia
      if: ${{ steps.cache.outputs.skip == 'false' }}
      shell: bash
      run: cargo install cydonia --version ${{ inputs.version }}
