[package]
name = "cydonia"
authors = [ "clearloop" ]
description = "The static site generator."
documentation = "https://docs.rs/cydonia"
version = "0.0.2"
edition = "2021"

[dependencies]
anyhow = "1.0.77"
chrono = "0.4.31"
colored = "2.1.0"
etc = { version = "0.1.18", features = [ "serde" ] }
handlebars = { version = "4.5.0", features = [ "dir_source" ] }
pulldown-cmark = { version = "0.9.3", default-features = false }
serde = { version = "1.0.193", features = [ "derive" ] }
serde_json = "1.0.108"
serde_yaml = "0.9.29"
toml = "0.8.8"
tracing = "0.1.40"

# Optional features for the cli
ccli = { version = "0.0.1", optional = true }
notify = { version = "6.1.1", optional = true }
tokio = { version = "1.35.1", optional = true }
warp = { version = "0.3.6", optional = true }

[features]
default = [ "cli" ]
cli = [ "ccli", "notify", "tokio", "warp" ]
